---

name: Build and deploy website

'on':
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy:
    uses: flokoe/server/.github/workflows/reusable-hugo-build-deploy.yml@main
    secrets: inherit
